# Following these manual: https://symfonycasts.com/screencast/messenger/sending-json
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # https://symfony.com/doc/current/messenger.html#transports
            external_messages:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\ExternalJsonMessageSerializer
                options:
                    # assume some other system will create this
                    auto_setup: true
                    # exchange config not needed because that's only
                    # for *sending* messages
                    exchange:
                        name: messages
                        type: fanout
                        default_publish_routing_key: from_external
                    queues:
                        messages_from_external:
                            binding_keys: [from_external]
        routing:
            #'App\GraphQL\Mutation\AddPonkaToImage': async_priority_high
            'App\Message\NewUserAdded': external_messages
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
