Mutation:
    type: object
    config:
        fields:
            add_user:
                type: NewUserPayload!
                resolve: "@=mutation('add_user', [args['input']['username'], args['input']['email'], args['input']['phoneNumber']])"
                args:
                    input: NewUserInput!

                    