PatientUsers:
    type: object
    config:
        fields:
            patientUsersUUID:
                type: "ID!"
            patientUUID:
                type: "String!"
            user:
                type: "User"