NewUserInput:
  type: input-object
  config:
    fields:     
      username:
        type: "String!"
        description: "User name"
      email:
        type: "String"
      phoneNumber:
        type: "String"

NewUserPayload:
  type: object
  config:
    fields:
      userUUID:
        type: "ID"
      username:
        type: "String!"
        description: "User name"
      email:
        type: "String"
      phoneNumber:
        type: "String"
      sagaStatus:
        type: "String"

      # hashtags:
      #   type: "[Hashtag]"
