Query:
    type: object
    config:
        description: 'Just one query'
        fields:
            allUsers:
                type: '[User]'
                resolve: "@=resolver('all_users', [args])"
            userById:
                type: 'User'
                resolve: "@=resolver('user_by_id', [args])"
                args:
                    id:
                        description: 'Resolves using user id'
                        type: 'ID'
            